context("check")

test_that("check_course works as expected", {
  course = list()
  expect_that(check_course_object(course), throws_error())
  course = list(title = "test")
  expect_that(check_course_object(course), throws_error())
  course = list(title = "test", author_field = "authortest")
  expect_that(check_course_object(course), throws_error())
  course = list(title = "", author_field = "authortest", description = "descriptiontest")
  expect_that(check_course_object(course), throws_error())
  course = list(title = "test", author_field = "authortest", description = "descriptiontest")
  expect_that(is.null(check_course_object(course)), is_true())
})

test_that("check_chapter works as expected", {
  course = list(title = "test", author_field = "authortest", description = "descriptiontest")
  course$chapters = list(list(chapter1.Rmd = 1))
  expect_that(check_course_object(course), throws_error())
  author_chapter("chapter1.Rmd", open = FALSE)
  expect_that(is.null(check_course_object(course)), is_true())
  course$chapters = list(list(chapter1.Rmd = 1), list(chapter1.Rmd = 2))
  expect_that(check_course_object(course), throws_error())
  course$chapters = list(list(chapter1.Rmd = 1), list(chapter2.Rmd = 1))
  expect_that(check_course_object(course), throws_error())
  course$chapters = list(list(chapter1.Rmd = 1), list(chapter2.Rmd = 2))
  expect_that(check_course_object(course), throws_error())
  author_chapter("chapter2.Rmd", open = FALSE)
  expect_that(is.null(check_course_object(course)), is_true())
  
  unlink("chapter1.Rmd")
  unlink("chapter2.Rmd")
})